config/routes.rb
Rails.application.routes.draw do

  root to: 'application#homepage'
  get '/' => 'application#homepage'
  get '/about' => 'application#about'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  patch '/:id' => 'users#update'
  post '/users' => 'users#create'
  patch '/:id' => 'users#update'

  get '/books' => 'channels#booksIndex'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get '/facebook' => 'application#facebook'
  get '/settings' => 'users#edit', as: 'edit_user'
  post '/twitter' => 'users#twitter'
  get '/facebookpostsretrieval' => 'users#facebook', as: 'facebook_posts_retreival'
  get '/analyzedata' => 'users#analyze_personality', as: 'analyze_data'

  get '/:username' => 'users#show', as: 'user'

  resources :sessions, only: [:create, :destroy]
  resources :users
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password(validations: false)
  # From paperclip
  has_attached_file :avatar, 
                    styles: { medium: "300x300>", thumb: "100x100>" }, 
                    default_url: "WATSON_NO_PIC.png",
                    :storage => :dropbox,
                    :dropbox_credentials => {app_key: ENV['DROPBOX_KEY'], 
                                            app_secret: ENV['DROPBOX_SECRET'], 
                                            access_token: ENV['DROPBOX_ACCESS_TOKEN'], 
                                            access_token_secret: ENV['DROPBOX_ACCESS_TOKEN_SECRET'], 
                                            user_id: ENV['USER_ID'], access_type: "app_folder"}
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  validates_confirmation_of :password, unless: -> { from_omniauth? }
  validates_presence_of :password, :on => :create, unless: -> { from_omniauth? }

	validates_presence_of :email, :notice => "Please include email", unless: -> { from_omniauth? }
	validates_uniqueness_of :email, :notice => "Email already taken", unless: -> { from_omniauth? }
	validates :username, length: {minimum: 3, maximum: 15}, :uniqueness => { :case_sensitive => false},
	  format: {
	    with: /\A[a-zA-Z0-9_-]+\z/,
	    message: 'Must be formatted correctly (no spaces)'
	  }, unless: -> { from_omniauth? }

  def self.from_omniauth(auth)
    unless auth.nil?
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.name = auth.info.name
        user.oauth_token = auth.credentials.token
        user.oauth_expires_at = Time.at(auth.credentials.expires_at)
        user.save!
      end
    end
  end

  private

  def from_omniauth?
    provider && uid
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authorize, only: [:edit, :update, :destroy]
  


  def show
    @user = User.find_by_username(params[:username]) || User.find_by_username(params[:username].capitalize)
    if(Personality.where(user_id: @user.id).count > 0)
      @big_5 = Personality.where(user_id: @user.id).where(category: "Big 5").group(:attribute_name).average(:percentage).sort_by{|k,v| v}
      @needs = Personality.where(user_id: @user.id).where(category: "Needs").group(:attribute_name).average(:percentage).sort_by{|k,v| v}
      @values = Personality.where(user_id: @user.id).where(category: "Values").group(:attribute_name).average(:percentage).sort_by{|k,v| v}
      @docSentiment = Topic.where(user_id: @user.id).where(name: "Document Sentiment").pluck(:relevance)[0].to_f
      @docSentimentLabel = Topic.where(user_id: @user.id).where(name: "Document Sentiment").pluck(:label)[0]
      if @docSentiment != 0.0
        @sentimentChartLg = LazyHighCharts::HighChart.new('graph') do |f|
          f.series(:name=>'Sentiment', :data=>[@docSentiment], :color=> '#E23246')
          f.options[:xAxis][:reversed] = false
          f.options[:xAxis][:labels] = { enabled:false }
          f.options[:yAxis][:labels] = { enabled:false }
          f.options[:yAxis][:max] = 1
          f.options[:yAxis][:min] = -1
          f.options[:yAxis][:tickInterval] = 1
          f.options[:legend][:enabled] = false
          f.chart({:defaultSeriesType=>"bar", :backgroundColor=>'#FCEDED', :height=>'125', :width=>'1000'})
        end
        @sentimentChartSm = LazyHighCharts::HighChart.new('graph') do |f|
          f.series(:name=>'Sentiment', :data=>[@docSentiment], :color=> '#E23246')
          f.options[:xAxis][:reversed] = false
          f.options[:xAxis][:labels] = { enabled:false }
          f.options[:yAxis][:labels] = { enabled:false }
          f.options[:yAxis][:max] = 1
          f.options[:yAxis][:min] = -1
          f.options[:yAxis][:tickInterval] = 1
          f.options[:legend][:enabled] = false
          f.chart({:defaultSeriesType=>"bar", :backgroundColor=>'#FCEDED', :height=>'100', :width=>'300'})
        end
      end
      
      # Gather Value and Labels for needs chart
      @needsValues = @needs.map{|x|(x[1]*100).round}
      @needsLabels = @needs.map{|x|(x[0])}
      @needsChartLg = LazyHighCharts::HighChart.new('graph') do |f|
        f.series(:name=>'Needs', :type=>'area', :data=>@needsValues, :color=> '#E23246')
        f.plotOptions(series: { :pointStart=>0, :pointInterval=>45})
        f.plotOptions(column: { :pointPadding=>0, :groupPadding=>0})
        f.xAxis[:tickInterval] = 45
        f.xAxis[:min] = 0
        f.xAxis[:max] = 360
        f.yAxis[:min] = 0
        f.options[:yAxis][:labels] = { enabled:false }
        f.options[:xAxis][:categories] = @needsLabels
        f.options[:legend][:enabled] = false
        f.chart({:polar => true, :backgroundColor=>'#FCEDED',:height=>'600', :width=>'600'})
      end
      @needsChartSm = LazyHighCharts::HighChart.new('graph') do |f|
        f.series(:name=>'Needs', :type=>'area', :data=>@needsValues, :color=> '#E23246')
        f.plotOptions(series: { :pointStart=>0, :pointInterval=>45})
        f.plotOptions(column: { :pointPadding=>0, :groupPadding=>0})
        f.xAxis[:tickInterval] = 45
        f.xAxis[:min] = 0
        f.xAxis[:max] = 360
        f.yAxis[:min] = 0
        f.options[:yAxis][:labels] = { enabled:false }
        f.options[:xAxis][:categories] = @needsLabels
        f.options[:legend][:enabled] = false
        f.chart({:polar => true, :backgroundColor=>'#FCEDED',:height=>'300', :width=>'300'})
      end
    else
      flash[:notice] = "Analyze tweets first"
      redirect_to edit_user_path(current_user.username)
    end
  end

  def analyze_personality
    if(!Channel.where(name: "twitter").where(user_id: current_user.id).empty?)
      Personality.where(user_id: current_user.id).where(channel_name: "twitter").delete_all
      Personality.personality(current_user.id, "twitter", "#{current_user.name}'s Twitter Account")
      Topic.where(user_id: current_user.id).where(channel_name: "twitter").delete_all
      Topic.alchemy(current_user.id, "twitter", "#{current_user.name}'s Twitter Account")
    else
      flash[:notice] = "No twitter content to analyze"
    end
    redirect_to user_path(current_user.username)
  end

  def twitter 
    @twitter_username = params[:twitter_username]
    @user = current_user
    @user.twitter_username = @twitter_username
    @user.save
    if Channel.where(user_id: @user.id).where(name: "twitter").first.nil?
      TwitterInfo.new.public_tweets(@twitter_username, current_user.id)
      render :text => "Stored tweets successfully!"
    else
      flash[:notice] = "Already stored tweets"
      redirect_to edit_user_path(current_user.username)
    end
  end

  def update
    @user = User.find(current_user.id)
    user_params = params.require(:user).permit(:name,:email,:username, :avatar)
    if @user.update_attributes(user_params)
      flash[:notice] = "Updated!"
      redirect_to "/settings"
    else 
      flash[:notice] = @user.errors.map{|k,v| "#{k} #{v}".capitalize}
      redirect_to "/settings"
    end
  end

  def edit
    @user = User.find(current_user.id)
    puts @user
    @twitter_count = Channel.where(user_id: current_user.id).where(name: "twitter").count
    @personality_count = Personality.where(user_id: current_user.id).count
  end

  def destroy
    if @user.id == current_user.id
      @user.destroy
      respond_to do |format|
        format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      redirect_to '/signup'
    end
  end

  def new
    if current_user
      redirect_to '/settings'
    end
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to '/settings'
    else
      flash[:notice] = user.errors.map{|k,v| "#{k} #{v}".capitalize}
      redirect_to '/signup'
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :avatar)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<div class="row">
	<div class="col-sm-3 user-bar hidden-xs">
		<div class="profile-headers text-center"><%= @user.name %></div>
		<div class="img-rounded">
			<%= image_tag @user.avatar.url(:medium), class: "img-responsive avatar image-resize"%>
		</div>
		<div class="profbar-wrapper">
			Joined on <%= @user.created_at.to_date.to_formatted_s(:long_ordinal) %><br><br><br>
			<div class="user-info">
				<div class="username">
					<%= @user.username %><br><br>
				</div>
				<div class="email">
					<%= @user.email %><br><br>
				</div> 
			</div>
		</div>
	</div>
	<div class="col-sm-3 user-bar-mobile  visible-xs">
		<div class="profile-headers text-center"><%= @user.name %></div>
		<div class="img-rounded-mobile col-xs-3">
			<%= image_tag @user.avatar.url(:medium), class: "img-responsive avatar image-resize"%>
		</div>
		<div class="profbar-wrapper">
			<div class="user-info">
				<div class="username">
					<%= @user.username %><br><br>
				</div>
				<div class="email">
					<%= @user.email %><br><br>
				</div> 
			</div>
		</div>
	</div>
	<div class="profile-content">
	<div class="col-md-12 banner text-center">
			<div class="half-banner"></div>
		</div>
		<div class="col-xs-10 col-sm-7 col-md-6 col-xs-offset-1 col-sm-offset-4  col-md-offset-3 signup-form">
			<div class="headers text-center">
				<h1>Edit your profile</h1>
			</div>

			<% if @twitter_count == 0 %>
				<br>
				<div class="tweets" id="retrieve-tweets">
					<p id="progress-bar-check"></p>
					<div class="progress hidden">
					  <div class="progress-bar progress-bar-info progress-bar-striped" role="progressbar" aria-valuenow="5" aria-valuemin="0" aria-valuemax="100" style="width: 1%" id="progress_bar">
					  </div>
					</div>
					<form id="retrieve-tweets-submit">
					  	<div class="form-group">
					  		<strong>Twitter handle</strong><input type="text" name="twitter_username" id="twitter_username" class="form-control" placeholder="">
					  	</div>
					  	<div class="form-group">
					    	<input type="submit" class="btn btn-default" value="Submit">
					  	</div>
					</form>
				</div>		
			<% end %>

			<div class="analyze hidden" id="analyze-tweets">
				<%= link_to "Analyze Twitter Data", analyze_data_path, class: 'btn btn-info', data: (@personality_count > 0 ? { confirm: 'Are you sure?' } : nil) %>
			</div>

			<% if @twitter_count > 0 %>
				<br>
					<%= link_to "Analyze Twitter Data", analyze_data_path, class: 'btn btn-info', data: (@personality_count > 0 ? { confirm: 'Are you sure?' } : nil) %><i><%= " Already pulled Tweets" %></i>
				<br>
			<% end %>
			<br>
			<%= form_for @user, html: { multipart: true } do |f| %>
				<div class="form-group">
					<%= f.label :avatar %>
					<%= f.file_field :avatar, class: "form-control" %>
				</div>
				<div class="form-group">
					<%= f.label :username %>
					<%= f.text_field :username, class: "form-control"%>
				</div>
				<div class="form-group">
					<%= f.label :name %>
					<%= f.text_field :name, class: "form-control" %>
				</div>
				<div class="form-group">
					<%= f.label :email %>
					<%= f.text_field :email, class: "form-control" %>
				</div>
				<div class="form-group">
					<%= f.submit "Submit", class: 'btn btn-default' %>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/users/new.html.erb
<div class="col-md-12 banner text-center">
	<div class="half-banner"></div>
</div>
<div class="col-xs-10 col-sm-6 col-md-4 col-xs-offset-1 col-sm-offset-3  col-md-offset-4 login-form">
	<div class="headers text-center">
		<h1>Signup!</h1>
	</div>
	<%= form_for :user, url: '/users' do |f| %>
		<div class="form-group">
			<%= f.label :username %>
			<%= f.text_field :username, class: "form-control"%>
		</div>
		<div class="form-group">
			<%= f.label :name %>
			<%= f.text_field :name, class: "form-control" %>
		</div>
		<div class="form-group">
			<%= f.label :email %>
			<%= f.text_field :email, class: "form-control" %>
		</div>
		<div class="form-group">
			<%= f.label :password %>
			<%= f.password_field :password, class: "form-control" %>
		</div>
		<div class="form-group">
			<%= f.label :password_confirmation %>
			<%= f.password_field :password_confirmation, class: "form-control" %>
		</div>
		<div class="form-group">
			<%= f.submit "Submit", class: 'btn btn-default' %>
		</div>
	<% end %>
</div>

app/views/users/show.html.erb
<div class="col-sm-3 user-bar hidden-xs">
		<div class="profile-headers text-center"><%= @user.name %></div>
		<div class="img-rounded">
			<%= image_tag @user.avatar.url(:medium), class: "img-responsive avatar image-resize"%>
		</div>
		<div class="profbar-wrapper">
			Joined on <%= @user.created_at.to_date.to_formatted_s(:long_ordinal) %><br><br><br>
			<div class="user-info">
				<div class="username">
					<%= @user.username %><br><br>
				</div>
				<div class="email">
					<%= @user.email %><br><br>
				</div> 
			</div>
		</div>
	</div>
	<div class="col-sm-3 user-bar-mobile  visible-xs">
		<div class="profile-headers text-center"><%= @user.name %></div>
		<div class="img-rounded-mobile col-xs-3">
			<%= image_tag @user.avatar.url(:medium), class: "img-responsive avatar image-resize"%>
		</div>
		<div class="profbar-wrapper">
			<div class="user-info">
				<div class="username">
					<%= @user.username %><br><br>
				</div>
				<div class="email">
					<%= @user.email %><br><br>
				</div> 
			</div>
		</div>
	</div>
	<div class="profile-content">
		<div class="col-md-12 banner text-center">
			<div class="half-banner"></div>
		</div>
		<div class="col-sm-12">
			<div class="chart-header text-center">
				Your tweets are mostly <%= @docSentimentLabel %>
			</div>
			<div class="chart">
				<% if @docSentiment != 0.0 %>
					<div class="visible-lg">
						<%= high_chart("SentimentGraphLg", @sentimentChartLg) %>
					</div>
					<div class="visible-xs">
						<%= high_chart("SentimentGraphSm", @sentimentChartSm) %>
					</div>
				<div class="chart-label">
					<div class="col-sm-4 col-xs-4">Negative</div>
					<div class="col-sm-4 col-xs-4 text-center" id="neutral">Neutral</div>
					<div class="col-sm-4 col-xs-4 text-right" id="positive">Positive</div>
				</div>
				<% end %>
			</div> 
			<span class="col-sm-3 col-sm-offset-1 traits">
				<div class="trait-headers"><a class="descriptors" tabindex="0" data-trigger="focus" data-toggle="popover" data-placement="top" data-container="body" data-content="How a person engages with the world. The Big Five:
					Agreeableness,
					Conscientiousness,
					Extraversion,
					Emotional Range, and 
					Openness. These dimensions are further characterized into subdimensions."><%= "Big 5" %></a>

				<!-- Generated markup by the plugin -->
				<div class="tooltip top" role="tooltip">
				  <div class="tooltip-arrow"></div>
				  <div class="tooltip-inner">

			  	  </div>
				</div>
			</div>
			
			<% @big_5.reverse.each do |attribute| %>
				<li><%= "#{attribute[0]}: #{(attribute[1].to_f*100).round(2)}%" %></li>
			<% end %>
			</span>
			<span class="col-sm-3 traits">
			<div class="trait-headers"><a class="descriptors" tabindex="0" data-trigger="focus" data-toggle="popover" data-placement="top" data-container="body" data-content="Describes at a high level which aspects of a product are likely to resonate with the writer of the content."><%= "Needs" %></a>

			<!-- Generated markup by the plugin -->
			<div class="tooltip top" role="tooltip">
			  <div class="tooltip-arrow"></div>
			  <div class="tooltip-inner">
			    
			  </div>
			</div>
			</div>

			<% @needs.reverse.each do |attribute| %>
				<li><%= "#{attribute[0]}: #{(attribute[1].to_f*100).round(2)}%" %></li>
			<% end %>
			</span>
			<span class="col-sm-3 traits">
			<div class="trait-headers"><a class="descriptors" tabindex="0" data-trigger="focus" data-toggle="popover" data-placement="top" data-container="body" data-content="Motivating factors that influence decision-making: Self-transcendence, Conservation, Hedonism, Self-enhancement, and Open to change."><%= "Values" %></a>

			<!-- Generated markup by the plugin -->
			<div class="tooltip top" role="tooltip">
			  <div class="tooltip-arrow"></div>
			  <div class="tooltip-inner">
			    Some tooltip text!
			  </div>
			</div>

			</div>
			<% @values.reverse.each do |attribute| %>
				<li><%= "#{attribute[0]}: #{(attribute[1].to_f*100).round(2)}%" %></li>
			<% end %>
			</span>
		</div>
		<div class="col-sm-5 col-sm-offset-2 hidden-xs">
			<%= high_chart("NeedsGraphLg", @needsChartLg) %>
		</div>
		<div class="col-xs-10 col-xs-offset-1 visible-xs">
			<%= high_chart("NeedsGraphSm", @needsChartSm) %>
		</div>
	</div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>