config/routes.rb
Rails.application.routes.draw do

  root to: 'application#homepage'
  get '/' => 'application#homepage'
  get '/about' => 'application#about'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  patch '/:id' => 'users#update'
  post '/users' => 'users#create'
  patch '/:id' => 'users#update'

  get '/books' => 'channels#booksIndex'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get '/facebook' => 'application#facebook'
  get '/settings' => 'users#edit', as: 'edit_user'
  post '/twitter' => 'users#twitter'
  get '/facebookpostsretrieval' => 'users#facebook', as: 'facebook_posts_retreival'
  get '/analyzedata' => 'users#analyze_personality', as: 'analyze_data'

  get '/:username' => 'users#show', as: 'user'

  resources :sessions, only: [:create, :destroy]
  resources :users
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="logo text-center">
      <%= image_tag "WATSON_LOGO.png", class: "logo" %>
    </div>
    <div class="navbar-left hidden-xs">
      <%= link_to "WATSON", root_path, class: "navbar-links" %>
    </div>
    <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#watson-navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
    </div>
    <div class="collapse navbar-collapse" id="watson-navbar">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
        <li><%= link_to "Home", "/", class: "navbar-links visible-xs" %></li>
        <li><%= link_to "Profile", "/#{current_user.username}", class: "navbar-links" %></li>
        <li><%= link_to "Settings", '/settings', class: "navbar-links" %></li>
        <li><%= link_to "Log out", logout_path, class: "navbar-links" %></li>
        <% else %>
        <li><%= link_to "Home", "/", class: "navbar-links visible-xs" %></li>
        <li><%= link_to "Sign up", new_user_path, class: "navbar-links" %></li>
        <li><%= link_to "Log in", login_path, class: "navbar-links" %></li>
        <% end %>
      </ul>
    </div>
</nav>

app/views/layouts/about.html.erb
<div class="about-body">
	<div class="row" id='about-title'>
		<%= "About" %>
	</div>

	<div class="row" id='about-project'>
	<%= "We built this application to aspire to better understand how we communicate with the world through social media, and to use this knowledge to gain new insights and information about ourselves. Combined with the desire to play with the IBM Watson APIs, we settled on pulling in personal twitter content to analyze personality traits, the positivity/negativity of our communication and more. In the future we're hoping to expand into analyzing other personal content as well as recommending content such as books or twitter accounts to follow. The application is named District Five for the elementary school that Thomas Watson attended." %>
	</div>

	<div class="row" id='meet-team'>
		<%= "Meet the team" %>
	</div>
	<div class="row">
		<div class="col-md-4">
			<a href="http://github.com/vframbach" target="_blank"><img src="https://scontent-yyz1-1.xx.fbcdn.net/hprofile-xpa1/v/t1.0-1/c50.50.621.621/7850_10101521377599033_1643181998_n.jpg?oh=af83fa2e7588e122d0dc6bb3b75e12e9&oe=57445D31" width="250" class="img-rounded" id="team-pic"></a>
		</div>
		<div class="col-md-4">
			<a href="http://github.com/abeytaadam" target="_blank"><img src="https://scontent-yyz1-1.xx.fbcdn.net/hprofile-xfa1/v/t1.0-1/c44.44.552.552/318281_3628122145481_1413888087_n.jpg?oh=d04ec3197fc3eac98f9deb9c58ba7f7c&oe=57063AF9" width="250" class="img-rounded" id="team-pic"></a>
		</div>
		<div class="col-md-4">
			<a href="http://github.com/Stanleyyork" target="_blank"><img src="https://scontent-yyz1-1.xx.fbcdn.net/hphotos-prn2/v/t1.0-9/1620629_10104303822941143_2659929500490146637_n.jpg?oh=13370ad11f2e5be9dfe7f3888bb43c9d&oe=57030EEB" width="250" class="img-rounded" id="team-pic"></a>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Watson</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="content-wrapper">

      <!-- navbar -->
      <%= render partial: '/layouts/nav' %>

      <!-- flash notice -->
      <% if flash[:notice] %>
      <div class="alert">
        <div class="alert alert-danger" role="alert">
          <% if flash[:notice].class != String %>
          <% flash[:notice].each do |f| %><br>
          <%= f %>
          <% end %>
          <% else %>
          <%= flash[:notice] %>
          <% end %>
        </div>
      </div>
      <% end %>
      <%= yield %>
    </div>
    <div class="footer text-center hidden-xs">
      <a class="about" href="/about">About</a>
    </div>
  </body>
</html>

app/views/layouts/homepage.html.erb
<div class="col-md-12 text-center homepage-body">
	<div class="col-md-12 homepage-heading text-center">
		<h1 class="title">WELCOME TO WATSON</h1>
	</div>
	<div class="info-pics">
		<div class="col-md-4 homepage-text-box">
			<div class="text-center">
				<h1>How It Works</h1>
				<%= image_tag "WATSON_WORD_BUB.png"%>
				<div class="homepage-text">Your Tweets will be <br> analyzed with Watson Personality Insights. Gain insight into your personality through content analysis.</div>
			</div>
		</div>
		<div class="col-md-4 homepage-text-box">
			<div class="text-center">
				<h1>Twitter</h1>
				<%= image_tag "WATSON_TWITTER.png"%>
				<div class="homepage-text">To get started, <br><a class = "signup-link" href="/users/new">Sign up for Watson</a><br> and enter in your Twitter username. The account must be public in order for the tweets to be analyzed.</div>
			</div>
		</div>
		<div class="col-md-4 homepage-text-box">
			<div class="text-center">
				<h1>Your Data</h1>
				<%= image_tag "WATSON_BAR.png"%>
				<div class="homepage-text">Receive a detailed breakdown of your top personality traits, based on your tweets. The analysis contains Big 5, Values, Needs, and Sentiment.</div>
			</div>
		</div>
	</div>
	<div class="col-md-8 col-md-offset-2 sample-pic">
	</div>
</div>